
/*切换tabbar*/
export const CHANGE_TAB = 'CHANGE_TAB';

/*用户登录成功，或者登录状态下*/
export const ACTION_LOGIN_SUCCESS = 'ACTION_LOGIN_SUCCESS';

export const ACTION_SET_MESSAGE_LIST_ICON = 'ACTION_SET_MESSAGE_LIST_ICON';   // 获取首页状态数量

export const ACTION_SET_VERIFIED_STATE = 'ACTION_SET_VERIFIED_STATE'; // 实名

export const ACTION_SET_CERTIFICATION_STATE = 'ACTION_SET_CERTIFICATION_STATE'; // 资质

export const ACTION_SET_CAR_NUM = 'ACTION_SET_CAR_NUM'; // 我的界面车牌号

